#############################################################################
## H2 Configuration
#############################################################################
spring:
  flyway:
    url: jdbc:h2:mem:football_player_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    schemas: FOOTBALL_PLAYER
    user: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
        path: /h2
  datasource:
    url: jdbc:h2:mem:football_player_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    driver-class-name: org.h2.Driver
  jpa:
    database: H2
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false



