#############################################################################
## Database Configuration
#############################################################################
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: embeded_db