INSERT INTO player_skills (
    player_id,
    season,
    create_date,
    attributes_json,
    traits,
    specialities,
    additionalInfo)
VALUES(
    319626f3-d429-4d10-ac64-bd7b6fde53e7,
    '2017-2018',
    '2099-11-13T00:00:00-02:00',
    '[{"category":"Physical","values":[{"name":"Acceleration","value":80},{"name":"Agility","value":75}]},{"category":"Technical","values":[{"name":"Ball Control","value":88}]}]',
    '["Diver","Playmaker"]',
    '["Dribbler","FK Specialist","Acrobat","Clinical","Finisher"]',
    '{"preferredFoot":"Left","internationalReputation":5,"WeakFoot":4,"skillMoves":4,"workRate":"Medium/Medium","bodyType":"Stocky","realFace":"true","releaseClause" : "€31.5M"}' );